services:
  nest-app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    command: ["npm", "run", "start:dev"]
  nest-test:
    build: .
    volumes:
      - .:/app 
      - /app/node_modules
    command: ["npm", "run", "test"]